---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: username/iss-tracker:1.0
        container_name: iss_tracker-app
        ports:
            - "5000:5000"
...
